vich_uploader:
    db_driver: orm

    mappings:
        quotePdf:
            uri_prefix: /upload/quote
            upload_destination: "%kernel.project_dir%/public/upload/quote"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
